2020-09-20 16:14:08,075 ERROR: Exception on /reset_password_request [POST] [in c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\routes.py", line 187, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\email.py", line 15, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-09-20 16:15:18,198 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:45]
2020-09-20 16:15:44,836 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:45]
2020-09-20 16:26:05,625 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:47]
2020-09-20 16:26:09,588 ERROR: Exception on /index [GET] [in c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\routes.py", line 45, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
